default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: binda_development

test:
  <<: *default
  host: localhost
  database: binda_test