toolbar:
  - styleselect | bold italic | undo redo | link image
plugins:
  - link
  - paste
  # - image

forced_root_block: false
paste_text_sticky_default: true 
paste_text_sticky: true
menubar: false
selector: '.tinymce'