toolbar:
  - bold italic | link image insert | undo redo | code
plugins:
  - link
  - paste
  - nonbreaking
  - autolink
  - code
  # - image

forced_root_block: false
paste_text_sticky_default: true
paste_text_sticky: true
menubar: edit format
selector: '.tinymce'