toolbar:
  - styleselect | bold italic | undo redo | link image
plugins:
  - link
  - paste
  - nonbreaking
  - autolink
  - code
  # - image

forced_root_block: false
paste_text_sticky_default: true
paste_text_sticky: true
menubar: edit format tools
selector: '.tinymce'